title = "todo-client"
description = ""
version = "0.1.0"
license = "MIT"
authors = [ "Your Name <you@example.com>" ]
keywords = ""

[build]
source = "src"
destination = "build"
target = "js"

[scripts]
test = "No tests specified"

[[servers]]
proto = "ww"
name = "default"

[[workers]]
proto = "ww"
count = "cpu"
server = "default"

[executor]
proto = "ww"
wait_for = "cpu"
server = "default"

# Npm specific configs

[npm]
browserslist = ["defaults", "not IE 11"]

[npm.devDependencies]
rollup = "^2.56.2"
sirv-cli = "^1.0.12"
clio-rollup = "latest"
"@babel/preset-env" = "^7.15.0"

[npm.scripts]
host = "node .clio/host.js"
build = "rollup -c"
dev = "rollup -c -w"
start = "npm run build && sirv public"
