title = "template-web"
description = ""
version = "0.1.0"
license = "MIT"
authors = [ "Your Name <you@example.com>" ]
keywords = ""

[build]
source = "src"
destination = "build"
target = "js"

[scripts]
test = "No tests specified"

[dependencies]
stdlib = "latest"

[[servers]]
proto = "ww"
name = "default"

[[workers]]
proto = "ww"
count = "cpu"
server = "default"

[executor]
proto = "ww"
wait_for = "cpu"
server = "default"


# Npm specific configs

[npm]
browserlist = ["> 0.2%", "not dead"]
main = "index.html"

[npm.alias]
ws = "clio-rpc/transports/ws/shim.js"
"main.clio.js" = "./main.clio.js"

[npm.devDependencies]
parcel = "next"

[npm.scripts]
start = "parcel index.html"
host = "node .clio/host.js"
build = "parcel build index.html"